;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
..=cd ..
::=exit
~=cd /d %USERPROFILE%
apm="%CMDER_ROOT%\vendor\atom\Atom\resources\app\apm\bin\apm $*"
atom="%CMDER_ROOT%\vendor\atom\Atom\atom $*"
bcompare="%CMDER_ROOT%\bin\BeyondCompare4\BCompare.exe"  

clear=cls
cmderr=cd %cmder_root%
cmderr=cd /d "%CMDER_ROOT%"
code="%CMDER_ROOT%\bin\vscode\code.exe" 2 $G null 
e.=explorer .
g=git $*
ga=git add -A $*
gam=git amend --reset-author $*
gap=git add --patch $*
gau=git add --update $*
gb=git branch $*
gba=git branch -a $*
gbd=git branch -d $*
gbib=git bisect bad $*
gbig=git bisect good $*
gbm=git branch -m $*
gbr=git recent-branches $*
gbs=git show-branch $*
gbv=git branch -v $*
gbx=git branch -D $*
gc=git commit $*
gca=git commit --amend --no-edit $*
gcar=git commit --amend --reuse-message HEAD $*
gcln=git clean $*
gclndf=git clean -df $*
gclndfx=git clean -dfx $*
gclnf=git clean -f $*
gclnn=git clean -n $*
gcm=git commit -m $*
gco=git checkout $*
gcoo=git checkout --ours -- $*
gcop=git checkout --patch $*
gcot=git checkout --theirs -- $*
gcp=git cherry-pick $*
gcpnc=git cherry-pick --no-commit $*
gcre=git revert $*
gcrsh=git reset "HEAD^" $*
gcrsp=git reset --patch $*
gcrsx=git reset --hard $*
gcs=git show $*
gcv=git commit --verbose $*
gcva=git commit --verbose --amend $*
gd=git diff $*
gdc=git diff --cached -w $*
gdi=git status --porcelain --short --ignored $B sed -n "s/^!! //p" $*
gdk=git ls-files --killed $*
gdm=git ls-files --modified $*
gdu=git ls-files --other --exclude-standard $*
gdx=git ls-files --deleted $*
gf=git fetch $*
gfc=git clone $*
gfch=git fetch $*
gfm=git pull $*
gfr=git pull --rebase $*
gg=git grep $*
ggfm=git grep --files-with-matches $*
ggfmv=git grep --files-without-matches $*
ggi=git grep --ignore-case $*
ggrc=git rebase --continue $*
ggw=git grep --word-regexp $*
gi=vim .gitignore $*
gid=git diff --no-ext-diff --cached $*
gidw=git diff --no-ext-diff --cached --word-diff $*
github=cd ^%userprofile^%\repos\github $*
gitlab=cd ^%userprofile^%\repos\gitlab $*
gl=git log --graph --date=short $*
gl=git log --oneline --all --graph --decorate  $*
glc=git shortlog --summary --numbered $*
glg=git log --graph --date=short --oneline --decorate $*
gm=git merge $*
gma=git merge --abort $*
gmnc=git merge --no-commit $*
gmnff=git merge --no-ff $*
gms=git merge --squash $*
gmt=git mergetool $*
gnb=git checkout -b $*
gnb=git nb $*
gp=git push $*
gpa=git push --all $*
gpat=git push --all $T$T git push --tags $*
gpf=git push --force $*
gpl=git pull $*
gplr=git pull --rebase $*
gps=git push $*
gpsa=git push --all $*
gpsf=git push --force $*
gpst=git push --tags $*
gr=git remote $*
gra=git remote add $*
grb=git rebase $*
grba=git rebase --abort $*
grbc=git rebase --continue $*
grbi=git rebase --interactive $*
grn=git remote rename $*
grp=git remote prune $*
grrm=git remote rm $*
grs=git reset $*
grsh=git remote show  $*
grsh=git reset --hard $*
grsp=git reset --patch $*
grsu=git remote set-url $*
gru=git remote update $*
grv=git remote -v $*
gs=git status $*
gsa=git stash apply $*
gsd=git stash drop $*
gsh=git show $*
gshd=git stash show --patch --stat $*
gsl=git stash list $*
gsm=git submodule $*
gsma=git submodule add $*
gsmf=git submodule foreach $*
gsmfpl=git submodule foreach git pull origin master $*
gsmi=git submodule init $*
gsms=git submodule status $*
gsmsy=git submodule sync $*
gsmu=git submodule update $*
gsmuir=git submodule update --init --recursive $*
gsp=git stash pop $*
gss=git stash save --include-untracked $*
gssp=git stash save --patch --no-keep-index $*
gt=git tag -n $*
gunc=git uncommit $*
guns=git unstage $*
history2=cat -n %CMDER_ROOT%\config\.history
history3=cat -n %CMDER_ROOT%\config\.history
history4=cat -n "%CMDER_ROOT%\config\.history"
history5=cat -n "C:\Users\user\cmder dev\config\.history"
history6=cat -n C:\Users\user\cmder dev\config\.history
home=cd /d %USERPROFILE%
intellij=D:\Users\296951\cmderdev\bin\intellij\bin\idea.bat  
jumpsever=mstsc -v UVAAMMPMIG01.maxcorp.maximus  
ll=ls -la --color $*
ls=ls --color $*
ls=ls --show-control-chars -F --color $*
myrepo=git remote -v $b grep origin $b head -n 1 $b cut -f 2 $b cut -d ' ' -f 1 $g %temp%\repo.tmp $t unix2dos %temp%\repo.tmp 2$lnull $t sleep 1 $t set /p x=$l%temp%\repo.tmp $t start /b %x%
myupstream=git remote -v $b grep upstream $b head -n 1 $b cut -f 2 $b cut -d ' ' -f 1 $g %temp%\repo.tmp $t unix2dos %temp%\repo.tmp 2$lnull $t sleep 1 $t set /p x=$l%temp%\repo.tmp $t start /b %x%
np=notepad $*
nvim="%CMDER_ROOT%\bin\neovim\bin\nvim.exe" $*
pip=python -m pip $*
portabletools="%CMDER_ROOT%\bin\brute-framework\start.bat" $*alias portabletools="%CMDER_ROOT%\bin\brute-framework\start.bat" $*exit  
pwd=cd
reinit3="%cmder_root%\vendor\init.bat" /maxdepth 3 /t
repos=cd "D:\Users\296951\repos\$1"
rinit=set "cmder_configured=" $t "%cmder_root%\vendor\init.bat" /d
rmccc=perl -pi -e 's/https:\/\/\S+?git-codecommit\.\S+?\.amazonaws.com\/\S+?$//g' %userprofile%/.git-credentials  
s=svn $*
sci=svn ci -m "$*"
sco=svn co $*
sd=svn diff | vim -R -
subl="%CMDER_ROOT%\bin\sublime_text\sublime_text.exe" $*
sublime_text="%CMDER_ROOT%\vendor\sublime_text_3\sublime_text"
subls="%CMDER_ROOT%\bin\sublime_text\sublime_text.exe" $* -new_console:s50V
sublv="%CMDER_ROOT%\bin\sublime_text\sublime_text.exe" $* -new_console:s50H
uhome=cd D:\Users\296951\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\home\dgames  
unalias=alias /d $1
va=vim "%CMDER_ROOT%\config\user_aliases.cmd"
vi=vim $*
vimdiff=vim -d $*

windowsterminal=D:\Users\296951\cmderdev\vendor\windows-terminal\windowsterminal.exe  
